USE master
GO

ALTER DATABASE Flicks4U SET SINGLE_USER WITH ROLLBACK IMMEDIATE

DROP DATABASE Flicks4U
DROP LOGIN administrador
DROP LOGIN gestorFunciones
DROP LOGIN recursosHumanos
DROP LOGIN visualizadorReportes